### ISSUE TITLE
Multi-Site Support

### ISSUE THREAD

**Issue by nightbook** [skyverge/woocommerce-customizer#14]
Hello,

I've installed your plugin on Multi-site and done a Network Activate however I don't find the Customizer tab added to the Woocommerce settings.
Does it not support multi-site?
Am I missing something.

Thanks

**Comment by bekarice** [comment]
Please see the [readme](https://github.com/skyverge/woocommerce-customizer/blob/master/readme.txt) notice / FAQ :smile:  

> **Note**: This plugin does not support multisite and cannot be network activated. To use this on a multisite network, you must install the plugin individually on each site.

**Comment by nightbook** [comment]
Thanks @bekarice overlooked that. Good to know. Cheers
