### ISSUE TITLE
ADD TO CART Button Change to View Product Button

### ISSUE THREAD

**Issue by thaziva** [skyverge/woocommerce-customizer#17]
Hi , I just wrote the short code about Chaning add to cart button to View Product Button but it is worked in ship 
but in simple product page, it is not worked, it shows read more button but when i clicked it , it is worked as the add to cart function.
Could you know how to solve it?
Thanks
&Regards
Thaziva

**Comment by bekarice** [comment]
@thaziva can you please include a screenshot of the setting you're referencing along with a link to which text isn't correct?
