### ISSUE TITLE
Thumbnails media changed to default image

### ISSUE THREAD

**Issue by gerbenb** [skyverge/woocommerce-customizer#19]
Hi there,
I set up a new default image in the plugin. Which worked. But now the thumbnails of uploaded files in products also show that default image in the Media Library (which makes it hard to see which image is which). If images are uploaded directly in the Media Library, the thumbnails are fine. It only occurs when uploading images in the Woocommerce environment (products).

**Comment by bekarice** [comment]
Hey @gerbenb sorry we missed this one! Looks like we didn't get alerted to this issue :(  can you show me a screenshot of what this looks like so I can replicate it?

**Comment by gerbenb** [comment]
![default-thumbnails](https://cloud.githubusercontent.com/assets/22539886/22694737/abc73dcc-ed48-11e6-85c4-6c60867633e9.jpg)

**Comment by gerbenb** [comment]
The green thumbnail is the default thumbnail. They show up here when I product upload images in products. The 'normal' images (blurred) are uploaded through the Media Library and shown alright.

**Comment by bekarice** [comment]
@gerbenb can you walk me through what you mean by "upload images in products"? Here's what I've done:

1. Uploaded a default image for a product.
2. Set the URL of that image as "Placeholder Image source" under WooCommerce > Settings > Customer > Misc
3. I've created other variations and products now, which will use this default.

No matter how many products I add, I still only have 1 default image in the media folder, so I don't think I'm following the same steps as you. Once I can replicate this we can determine how it would need to be fixed :)

**Comment by gerbenb** [comment]
Ok, I think I forgot to mention an important 'detail': I'm using the plugin 'Avenir-soft Direct Download' to upload images in the product. (Users are buying images which they can download). This plugin creates extra upload fields with the product. See the screenshot. The images uploaded here are not shown in the grid; instead the placeholder image is shown. 
The images are correctly shown when I turn of the Woocommerce Customize plugin.

**Comment by gerbenb** [comment]
![default-thumbnails2](https://cloud.githubusercontent.com/assets/22539886/22742131/f7561178-ee15-11e6-8d3e-61c1d81302ac.jpg)

**Comment by bekarice** [comment]
@gerbenb thanks for that! I'm now able to see this. So here's what happens:

1. When I have a downloadable WooCommerce product, and I add a file for it, the media folder will always show the **placeholder image** for that file, regardless of what kind of file that is. [Here's the code that does so](https://github.com/woocommerce/woocommerce/blob/91c68d211f1fb60e709e08cba17153a614d6b98f/includes/wc-product-functions.php#L454-L460).

2. When our plugin comes along, it filters _what_ that placeholder image should be. However, it does so everywhere, not just within your shop. As a result, the placeholders are changed in the admin as well.

To fix this, I'm going to ensure we only change what the placeholder image is when the shop / frontend is being viewed, not within the admin.

We'll include this in the next release, probably within a month or so to add WooCommerce 2.7 compatibility :) thanks!
