### ISSUE TITLE
COD hide message not showing on checkout page

### ISSUE THREAD

**Issue by preetmtharu** [skyverge/woocommerce-customizer#20]
Hello,

I have an issue on checkout page ,  i have enter postal codes where COD is not available, but when i check is it working or not then i found that only COD field's display hide but message of COD hide message field is not showing. Please help me ASAP..

**Comment by bekarice** [comment]
hey @preetmtharu I'm afraid that our Customizer doesn't adjust gateway availability or messaging / descriptions, so this issue isn't one the Customizer can address.
