### ISSUE TITLE
WC 2.7 Compatibility

### ISSUE THREAD

**Issue by bekarice** [skyverge/woocommerce-customizer#21]
### PR in #22

 - [x] **Misc** -- Drop support for WooCommerce < 2.5
   - ~~favor `$product->get_id()` where needed~~

- [x] **Misc** -- Add support for WooCommerce 2.7
   - ~~Replace usages of `$product->get_child(` with `wc_get_product(`~~

- [x] Update tested up to / requires versions

- [x] Update readme + changelog

**Comment by justinstern** [comment]
:ant:
