### ISSUE TITLE
Customize "Sale" flash text

### ISSUE THREAD

**Issue by bekarice** [skyverge/woocommerce-customizer#23]
### PR in #24 

Add a setting to customize the output of the "Sale" flash text via `woocommerce_sale_flash` filter

   * **Requested by**: [WP org thread](https://wordpress.org/support/topic/allow-for-customising-the-sale-flash-text/)
   * **Completed in**: SHA 07b55fd3c49fcc10ccec5e4df39d5cda747bbbcd

**Comment by bekarice** [comment]
Basic gist of what it does (can also use a set string like "Save!" instead):

![screen shot 2017-05-14 at 7 18 04 pm](https://cloud.githubusercontent.com/assets/4983547/26038620/52d8908e-38da-11e7-9a8d-d96e84d22e2c.png)

**Comment by ChaseWiseman** [comment]
LGTM 👍

**Comment by bekarice** [comment]
closed via #24
