### ISSUE TITLE
not working on woocommerce 3.0.3

### ISSUE THREAD

**Issue by paulgeek** [skyverge/woocommerce-customizer#25]
installed the plugin on wordpress 4.7.5 with woocommerce 3.0.3 . not working

**Comment by bekarice** [comment]
@paulgeek thanks for the report here! I've tested the plugin with both of these, and I'm afraid I can't replicate any issues. can you please let me know the following:

1. What you expect to see
2. What you actually see
3. If you still see an issue when using a default theme (like Twenty Seventeen) and with all plugins except WooCommerce + WC Customizer deactivated?

thanks!

**Comment by bekarice** [comment]
closing without feedback, please feel free to re-open if we've got steps or details to add 😸
