### ISSUE TITLE
Plugin not working upon installation

### ISSUE THREAD

**Issue by CBDHempTemple** [skyverge/woocommerce-customizer#32]
Hey, I just installed and activated the plugin but I'm getting now add to cart buttons anywhere. Please help

**Comment by bekarice** [comment]
hey there! I'm afraid this isn't an issue I've seen or can replicate, so I'm going to close this report. Our support team would be happy to assist in troubleshooting though! You can [reach out here](https://www.skyverge.com/contact/?form_type=support&purchased=wordpress). 🙂
