### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by rodolphebertozzo** [skyverge/woocommerce-customizer#36]
Is it possible to have a translation of Woocommerce Customizer in French ?

**Comment by unfulvio** [comment]
Hey @rodolphebertozzo thanks for reaching out.

We'd be happy to bundle a French translation to the plugin's next release in case you'd like to supply. 

You could do so by opening a pull request here, or contacting us via https://www.skyverge.com/contact/

Thank you and happy holidays

**Comment by unfulvio** [comment]
@rodolphebertozzo 

Oh, I forgot that WooCommerce Customizer is distributed via wordpress.org

That's even easier: you can simply translate the plugin via this handy interface provided by the WordPress plugin directory: https://translate.wordpress.org/projects/wp-plugins/woocommerce-customizer/

In this case we don't even need to issue a new release once a language support covers 100% of the plugin; language packs are managed straight from WordPress.org.

Someone already started it for French: https://translate.wordpress.org/locale/fr/default/wp-plugins/woocommerce-customizer/

I'm going to close this now, feel free to reply if you have further comments. 

Cheers
