### ISSUE TITLE
Change in `woocommerce_checkout_coupon_message` filter

### ISSUE THREAD

**Issue by tamarazuk** [skyverge/woocommerce-customizer#8]
WooCommerce lovingly [included the full coupon message](https://github.com/woothemes/woocommerce/commit/dc9043f99cc3c1f12c495a233ed0f9017332b458) in the `woocommerce_checkout_coupon_message` filter.

I see a few options in dealing with this

1. Ask users to enter in the full message including the anchor. The most flexible/easiest option of the 3 but not backwards compatible. Users will need to update their settings to continue reaping the benefits.

   ```
   Have a coupon? <a href="#" class="showcoupon">Click here to enter your code</a>
   ```

2. Add an else if [here](https://github.com/skyverge/woocommerce-customizer/blob/master/woocommerce-customizer.php#L163) for this filter and hook in a custom method that does one of the following:

   a. Replaces the text without removing the anchor link. User enters "Do you have a coupon?" and sees Do you have a coupon? <a href="#" class="showcoupon">Click here to enter your code</a>

   b. Add an additional setting to change the "Click here to enter your code" text and use both setting values on the filter

**Comment by bekarice** [comment]
I would vote for 2b, and combine "Coupon Notice Text" + "Coupon Link Text" settings to create this, as I think it would be easiest for users to understand. Perhaps a placeholder with what's there in core would help illustrate the point.

If we're going with something like 1 still, I think we'd have to include that as a setting description / add instructions to the FAQ, but I think it's a bit less user-friendly.
